/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkColorMaterialHelper_vs string.
 *
 */
#ifndef __vtkColorMaterialHelper_vs_h
#define __vtkColorMaterialHelper_vs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkColorMaterialHelper_vs;

#endif /* #ifndef __vtkColorMaterialHelper_vs_h */
