/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkDepthPeeling_fs string.
 *
 */
#ifndef __vtkDepthPeeling_fs_h
#define __vtkDepthPeeling_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkDepthPeeling_fs;

#endif /* #ifndef __vtkDepthPeeling_fs_h */
