/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkGaussianBlurPassShader_fs string.
 *
 */
#ifndef __vtkGaussianBlurPassShader_fs_h
#define __vtkGaussianBlurPassShader_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkGaussianBlurPassShader_fs;

#endif /* #ifndef __vtkGaussianBlurPassShader_fs_h */
