/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkLighting_s string.
 *
 */
#ifndef __vtkLighting_s_h
#define __vtkLighting_s_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkLighting_s;

#endif /* #ifndef __vtkLighting_s_h */
