/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkLightingHelper_s string.
 *
 */
#ifndef __vtkLightingHelper_s_h
#define __vtkLightingHelper_s_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkLightingHelper_s;

#endif /* #ifndef __vtkLightingHelper_s_h */
