/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkOpenGLRenderer_PeelingFS string.
 *
 */
#ifndef __vtkOpenGLRenderer_PeelingFS_h
#define __vtkOpenGLRenderer_PeelingFS_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkOpenGLRenderer_PeelingFS;

#endif /* #ifndef __vtkOpenGLRenderer_PeelingFS_h */
