/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkOpenGLPropertyDefaultMain_fs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultMain_fs_h
#define __vtkOpenGLPropertyDefaultMain_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkOpenGLPropertyDefaultMain_fs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultMain_fs_h */
