/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkOpenGLPropertyDefaultPropFunc_vs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultPropFunc_vs_h
#define __vtkOpenGLPropertyDefaultPropFunc_vs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkOpenGLPropertyDefaultPropFunc_vs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultPropFunc_vs_h */
