/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkOpenGLPropertyDefaultPropFunc_fs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultPropFunc_fs_h
#define __vtkOpenGLPropertyDefaultPropFunc_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkOpenGLPropertyDefaultPropFunc_fs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultPropFunc_fs_h */
