/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkOpenGLPropertyDefaultMain_vs string.
 *
 */
#ifndef __vtkOpenGLPropertyDefaultMain_vs_h
#define __vtkOpenGLPropertyDefaultMain_vs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkOpenGLPropertyDefaultMain_vs;

#endif /* #ifndef __vtkOpenGLPropertyDefaultMain_vs_h */
