/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkSobelGradientMagnitudePassShader2_fs string.
 *
 */
#ifndef __vtkSobelGradientMagnitudePassShader2_fs_h
#define __vtkSobelGradientMagnitudePassShader2_fs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkSobelGradientMagnitudePassShader2_fs;

#endif /* #ifndef __vtkSobelGradientMagnitudePassShader2_fs_h */
