/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkShadowMapPassShader_vs string.
 *
 */
#ifndef __vtkShadowMapPassShader_vs_h
#define __vtkShadowMapPassShader_vs_h

#include "vtkRenderingOpenGLModule.h"

VTKRENDERINGOPENGL_EXPORT extern const char *vtkShadowMapPassShader_vs;

#endif /* #ifndef __vtkShadowMapPassShader_vs_h */
