/*=Plus=header=begin======================================================
  Program: Plus
  Copyright (c) Laboratory for Percutaneous Surgery. All rights reserved.
  See License.txt for details.
=========================================================Plus=header=end*/

// This file is automatically generated from PlusExport.h.in by GENERATE_EXPORT_DIRECTIVE_FILE macro.

// .NAME __vtkCalibrationAlgoExport - manage Windows system differences
// .SECTION Description
// The __vtkCalibrationAlgoExport manages DLL export syntax differences
// between different operating systems.

#ifndef __vtkCalibrationAlgoExport_h
#define __vtkCalibrationAlgoExport_h

#if defined(WIN32) && !defined(vtkCalibrationAlgo_STATIC)
 #if defined(vtkCalibrationAlgo_EXPORTS)
  #define vtkCalibrationAlgoExport __declspec( dllexport )
 #else
  #define vtkCalibrationAlgoExport __declspec( dllimport )
 #endif
#else
 #define vtkCalibrationAlgoExport
#endif

#endif
