/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkLineIntegralConvolution2D_LIC0 string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_LIC0_h
#define __vtkLineIntegralConvolution2D_LIC0_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkLineIntegralConvolution2D_LIC0;

#endif /* #ifndef __vtkLineIntegralConvolution2D_LIC0_h */
