/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkLineIntegralConvolution2D_VT string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_VT_h
#define __vtkLineIntegralConvolution2D_VT_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkLineIntegralConvolution2D_VT;

#endif /* #ifndef __vtkLineIntegralConvolution2D_VT_h */
