/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkSurfaceLICPainter_GeomVs string.
 *
 */
#ifndef __vtkSurfaceLICPainter_GeomVs_h
#define __vtkSurfaceLICPainter_GeomVs_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_GeomVs;

#endif /* #ifndef __vtkSurfaceLICPainter_GeomVs_h */
