/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkSurfaceLICPainter_DCpy string.
 *
 */
#ifndef __vtkSurfaceLICPainter_DCpy_h
#define __vtkSurfaceLICPainter_DCpy_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_DCpy;

#endif /* #ifndef __vtkSurfaceLICPainter_DCpy_h */
