/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkSurfaceLICPainter_CE string.
 *
 */
#ifndef __vtkSurfaceLICPainter_CE_h
#define __vtkSurfaceLICPainter_CE_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_CE;

#endif /* #ifndef __vtkSurfaceLICPainter_CE_h */
