/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkSurfaceLICPainter_GeomFs string.
 *
 */
#ifndef __vtkSurfaceLICPainter_GeomFs_h
#define __vtkSurfaceLICPainter_GeomFs_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_GeomFs;

#endif /* #ifndef __vtkSurfaceLICPainter_GeomFs_h */
