/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkStructuredGridLIC2D_fs string.
 *
 */
#ifndef __vtkStructuredGridLIC2D_fs_h
#define __vtkStructuredGridLIC2D_fs_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkStructuredGridLIC2D_fs;

#endif /* #ifndef __vtkStructuredGridLIC2D_fs_h */
