/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkSurfaceLICPainter_SC string.
 *
 */
#ifndef __vtkSurfaceLICPainter_SC_h
#define __vtkSurfaceLICPainter_SC_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_SC;

#endif /* #ifndef __vtkSurfaceLICPainter_SC_h */
