/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkGPUVolumeRayCastMapper_AdditiveCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_AdditiveCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_AdditiveCroppingFS_h */
