/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFS_h */
