/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkHAVSVolumeMapper_k2EndFP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_k2EndFP_h
#define __vtkHAVSVolumeMapper_k2EndFP_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkHAVSVolumeMapper_k2EndFP;

#endif /* #ifndef __vtkHAVSVolumeMapper_k2EndFP_h */
