/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkHAVSVolumeMapper_kbufferVP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_kbufferVP_h
#define __vtkHAVSVolumeMapper_kbufferVP_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkHAVSVolumeMapper_kbufferVP;

#endif /* #ifndef __vtkHAVSVolumeMapper_kbufferVP_h */
