/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkProjectedAAHexahedraMapper_FS string.
 *
 */
#ifndef __vtkProjectedAAHexahedraMapper_FS_h
#define __vtkProjectedAAHexahedraMapper_FS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkProjectedAAHexahedraMapper_FS;

#endif /* #ifndef __vtkProjectedAAHexahedraMapper_FS_h */
