/* DO NOT EDIT.
 * Generated by /home/snr/Support/Plus-build-codeblocks/bin/vtkEncodeString-6.2
 * 
 * Declare the vtkVolumeTextureMapper3D_FourDependentShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_FourDependentShadeFP_h
#define __vtkVolumeTextureMapper3D_FourDependentShadeFP_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkVolumeTextureMapper3D_FourDependentShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_FourDependentShadeFP_h */
