set(ITKIOGIPL_LOADED 1)
set(ITKIOGIPL_DEPENDS "ITKIOImageBase;ITKZLIB")
set(ITKIOGIPL_LIBRARIES "ITKIOGIPL")
set(ITKIOGIPL_INCLUDE_DIRS "/home/snr/Support/Plus-build-codeblocks/itk/Modules/IO/GIPL/include")
set(ITKIOGIPL_LIBRARY_DIRS "")

