set(ITKIOJPEG_LOADED 1)
set(ITKIOJPEG_DEPENDS "ITKIOImageBase;ITKJPEG")
set(ITKIOJPEG_LIBRARIES "ITKIOJPEG")
set(ITKIOJPEG_INCLUDE_DIRS "/home/snr/Support/Plus-build-codeblocks/itk/Modules/IO/JPEG/include")
set(ITKIOJPEG_LIBRARY_DIRS "")

