# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "NSIS;ZIP")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/home/snr/Support/Plus-build-codeblocks/PlusApp-bin;PlusApp;ALL;/;/home/snr/Support/Plus-build-codeblocks/PlusLib-bin;PlusLib;RuntimeExecutables;/;/home/snr/Support/Plus-build-codeblocks/PlusLib-bin;PlusLib;RuntimeLibraries;/;/home/snr/Support/Plus-build-codeblocks/PlusLib-bin;PlusLib;Scripts;/;/home/snr/Support/Plus-build-codeblocks/vtk-bin;VTK;RuntimeLibraries;/;/home/snr/Support/Plus-build-codeblocks/itk-bin;ITK;RuntimeLibraries;/;/home/snr/Support/Plus-build-codeblocks/OpenIGTLink-bin;OpenIGTLink;RuntimeLibraries;/")
SET(CPACK_INSTALL_PREFIX "/home/snr/Support/Plus-build-codeblocks/PlusApp-bin/Install")
SET(CPACK_MODULE_PATH "/home/snr/Support/Plus-build-codeblocks/vtk/CMake")
SET(CPACK_NSIS_DEFINES "RequestExecutionLevel user")
SET(CPACK_NSIS_DISPLAY_NAME "PlusApp-2.3.0.4221-Linux/Mac")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROFILE")
SET(CPACK_NSIS_PACKAGE_NAME "Plus Applications 2.3.0.4221 (Linux/Mac)")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/snr/Support/Plus-build-codeblocks/PlusApp-bin/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Plus (Public software Library for UltraSound) for Linux/Mac")
SET(CPACK_PACKAGE_EXECUTABLES "PlusServerLauncher;Plus server;fCal;Free-hand calibration (fCal)")
SET(CPACK_PACKAGE_FILE_NAME "PlusApp-2.3.0.4221-Linux/Mac")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "PlusApp-2.3.0.4221-Linux/Mac")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "PlusApp-2.3.0.4221-Linux/Mac")
SET(CPACK_PACKAGE_NAME "PlusApp")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "PerkLab, Queen's University")
SET(CPACK_PACKAGE_VERSION "2.3.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "2")
SET(CPACK_PACKAGE_VERSION_MINOR "3")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/snr/Support/Plus-build-codeblocks/PlusLib/src/License.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;TZ")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/snr/Support/Plus-build-codeblocks/PlusApp-bin/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
