# CMake generated Testfile for 
# Source directory: /home/snr/Support/Plus-build-codeblocks/PlusApp/CommonWidgets/Testing
# Build directory: /home/snr/Support/Plus-build-codeblocks/PlusApp-bin/CommonWidgets/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(DeviceSetSelectorWidgetTest "/home/snr/Support/Plus-build-codeblocks/PlusLib/tools/Sikuli/Sikuli-IDE.exe" "-stderr" "-run" "/home/snr/Support/Plus-build-codeblocks/PlusApp/CommonWidgets/Testing/DeviceSetSelectorWidgetTest.sikuli" "--args" "/home/snr/Support/Plus-build-codeblocks/bin/SegmentationParameterDialogTest" "--device-set-configuration-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing" "--image-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/TestImages")
SET_TESTS_PROPERTIES(DeviceSetSelectorWidgetTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
ADD_TEST(StatusIconTest "/home/snr/Support/Plus-build-codeblocks/PlusLib/tools/Sikuli/Sikuli-IDE.exe" "-stderr" "-run" "/home/snr/Support/Plus-build-codeblocks/PlusApp/CommonWidgets/Testing/StatusIconTest.sikuli" "--args" "/home/snr/Support/Plus-build-codeblocks/bin/SegmentationParameterDialogTest" "--device-set-configuration-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing" "--config-file=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing/PlusDeviceSet_fCal_SonixTouch_L14-5_Ascension3DG_1.0.xml" "--image-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/TestImages")
SET_TESTS_PROPERTIES(StatusIconTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
ADD_TEST(SegmentationParameterDialogTest "/home/snr/Support/Plus-build-codeblocks/PlusLib/tools/Sikuli/Sikuli-IDE.exe" "-stderr" "-run" "/home/snr/Support/Plus-build-codeblocks/PlusApp/CommonWidgets/Testing/SegmentationParameterDialogTest.sikuli" "--args" "/home/snr/Support/Plus-build-codeblocks/bin/SegmentationParameterDialogTest" "--device-set-configuration-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing" "--config-file=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing/PlusDeviceSet_SegmentationParameterDialog_SavedDataset_1.0.xml" "--image-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/TestImages")
SET_TESTS_PROPERTIES(SegmentationParameterDialogTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
ADD_TEST(ConfigFileSaverDialogTest "/home/snr/Support/Plus-build-codeblocks/PlusLib/tools/Sikuli/Sikuli-IDE.exe" "-stderr" "-run" "/home/snr/Support/Plus-build-codeblocks/PlusApp/CommonWidgets/Testing/ConfigFileSaverDialogTest.sikuli" "--args" "/home/snr/Support/Plus-build-codeblocks/bin/SegmentationParameterDialogTest" "--device-set-configuration-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing" "--config-file=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing/PlusDeviceSet_SegmentationParameterDialog_SavedDataset_1.0.xml" "--image-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/TestImages" "--verify-saved-configuration-file")
SET_TESTS_PROPERTIES(ConfigFileSaverDialogTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
ADD_TEST(ToolStateDisplayWidgetTest "/home/snr/Support/Plus-build-codeblocks/PlusLib/tools/Sikuli/Sikuli-IDE.exe" "-stderr" "-run" "/home/snr/Support/Plus-build-codeblocks/PlusApp/CommonWidgets/Testing/ToolStateDisplayWidgetTest.sikuli" "--args" "/home/snr/Support/Plus-build-codeblocks/bin/ToolStateDisplayWidgetTest" "--device-set-configuration-dir=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing" "--config-file=/home/snr/Support/Plus-build-codeblocks/PlusLib/data/ConfigFiles/Testing/PlusDeviceSet_FakeTracker_ToolState.xml")
SET_TESTS_PROPERTIES(ToolStateDisplayWidgetTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
