/*=Plus=header=begin======================================================
  Program: Plus
  Copyright (c) Laboratory for Percutaneous Surgery. All rights reserved.
  See License.txt for details.
=========================================================Plus=header=end*/

// This file is automatically generated from PlusExport.h.in by GENERATE_EXPORT_DIRECTIVE_FILE macro.

// .NAME __vtkUsSimulatorAlgoExport - manage Windows system differences
// .SECTION Description
// The __vtkUsSimulatorAlgoExport manages DLL export syntax differences
// between different operating systems.

#ifndef __vtkUsSimulatorAlgoExport_h
#define __vtkUsSimulatorAlgoExport_h

#if defined(WIN32) && !defined(vtkUsSimulatorAlgo_STATIC)
 #if defined(vtkUsSimulatorAlgo_EXPORTS)
  #define vtkUsSimulatorAlgoExport __declspec( dllexport )
 #else
  #define vtkUsSimulatorAlgoExport __declspec( dllimport )
 #endif
#else
 #define vtkUsSimulatorAlgoExport
#endif

#endif
